pseeder:
  port: 2342
  download_path: '/tmp/p-seeder-engine'

  monitor:
    api: 'localhost:3001/api'
    announce: 'localhost:8000/announce'
    ws: 'ws://localhost:7894'

  papi: 'localhost:8001/'
