---
swagger: '2.0'

info:
  version: "0.1.0"
  title: P-Seeder-Engine
  description: P-Project P-Seeder-Engine
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT

schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json


paths:
  /torrent/:
    get:
      summary: List torrents
      description: List all loaded torrent identifiers
      responses:
        200:
          description: An array of identifiers.
          schema:
            type: array
            items:
              type: string
              format: hash
    post:
      summary: Create torrent from path
      description: Create and add a new torrent from a file path
      parameters:
        - name: title
          in: query
          description: Torrent title
          type: string
        - name: description
          in: query
          description: Torrent description
          type: string
        - name: path
          in: query
          description: The path of the file to seed
          type: string
          format: path
      responses:
        200:
          description: Torrent identifier
          schema:
            type: object
            properties:
              id:
                type: string
                format: hash
              uploadDate:
                type: number
              metadata:
                type: object
                properties:
                  height:
                    type: number
                  width:
                    type: number
                  format:
                    type: number
                  hash:
                    type: string
                    format: hash
              categories:
                type: array
                items:
                  type: string
        default:
          description: Video path incorrect or torrent already added
          schema:
            $ref: '#/definitions/Error'
      
  /torrent/{id}:
    get:
      summary: List torrents
      description: List all loaded torrent identifiers
      parameters:
        - name: id
          in: path
          description: The torrent identifier (usually, infohash)
          required: true
          type: string
          format: hash
      responses:
        200:
          description: Torrent information
          schema:
            type: object
            properties:
              name:
                type: string
              id:
                type: string
                format: hash
              timeRemaining:
                type: number
              received:
                type: number
              downloaded:
                type: number
              uploaded:
                type: number
              downloadSpeed:
                type: number
              uploadSpeed:
                type: number
              progress:
                type: number
              length:
                type: number
              ratio:
                type: number
              numPeers:
                type: number
              path:
                type: string
        default:
          description: InfoHash parsing / Torrent not found
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Add torrent
      description: Add a torrent from an identifier
      parameters:
        - name: id
          in: path
          description: Torrent identifier (usually, infohash)
          required: true
          type: string
          format: hash
      responses:
        200:
          description: Torrent identifier
          schema:
            type: string
            format: hash
        default:
          description: Identifier incorrect or torrent already added
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: Remove torrent
      description: |
        Delete a torrent by infohash
      parameters:
        - name: id
          in: path
          description: Torrent identifier
          required: true
          type: string
          format: hash
      responses:
        200:
          description: Torrent identifier
          schema:
            type: string
            format: hash
        default:
          description: InfoHash parsing / Torrent not found
          schema:
            $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      id:
        type: integer
        format: int32
      msg:
        type: string
      status:
        type: string
